* python-mode

Note that there is a package called python-mode.el which would replace the built-in python mode.

** anaconda or elpy
Anaconda is supposed to be more lightweight and minimal whereas elpy is supposed to be a complete environment.
Prelude and spacemacs both use anaconda mode because it is easier to integrate with their setup.

** blacken
Automatic code formatting.

** company-jedi or company-anaconda
This makes ctags, etags or gtags unnecessary for python.
It is a completion mechanism.

** company
Not sure if this is necessary but also allows integration with Yasnippet and such.

** yasnippet
Automatic code snippets.

** configure line length and wrapping

** flycheck or flymake (if want to check on save)
Automatic code syntax checking.

** projectile and counsel-projectile (for ivy integration)
Project management

** neotree (not sure I like this)
Visual file layout

** flake8 (or pylint but I think flake8 is better in this case)
Linter that links into flycheck.

** pyenv-mode
Ability to select virtual environment and integrate with projectile.

** magit
Should probably get magit working.

** command to comment or uncomment blocks

** improved navigation

** jupyter notebook?

** python shell?

** interactive shell?

** tests?

** refactoring capabilities (ropemacs)?
